spring:
  h2:
    console.enabled: true
  jpa:
    defer-datasource-initialization: true
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:~/unicorn;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=9092;USER=sa;PASSWORD=admin
    driver-class-name: org.h2.Driver

---

spring:
  config:
    activate:
      on-profile: init-persistence

  sql:
    init:
      mode: always

---

spring:
  config:
    activate:
      on-profile: no-init-persistence

  sql:
    init:
      mode: never

---

spring:
  config:
    activate:
      on-profile: in-memory-db-persistence

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver